//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public int Subject_id { get; set; }
        public string Properties { get; set; }
        public Nullable<int> VisualRepresentation_Id { get; set; }
        public Nullable<int> Description_Id { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual VisualRepresentation VisualRepresentation { get; set; }
    }
}
