//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logs
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string MessageId { get; set; }
        public int Level { get; set; }
        public string Application { get; set; }
        public byte[] Exception { get; set; }
    }
}
